#!/bin/sh

if ! [ -s ~/.cache/corona ] 
then
	rm -f ~/.cache/corona
	curl -s https://corona-stats.online/Serbia > ~/.cache/corona
else
	[ "$(date -r ~/.cache/corona "+%Y-%m-%d" | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] && 
		curl -s https://corona-stats.online/Serbia > ~/.cache/corona &&
		echo "Obnovljeno"
fi

grep "Serbia" ~/.cache/corona |
	sed "s/\s*//g ; s/║//g ; s/│/;/g" |
	awk -F';' '{print "Zaraženi: " $3 " (" $4") Umrli: " $5 " (" $6 ")"}'

